# .air.toml

[build]
  cmd = "go build -o ./tmp/main ."   
  bin = "tmp/main"                   
  full_bin = "tmp/main"
  include_ext = ["go", "yaml", "toml", "json"] 
  exclude_dir = ["tmp", "vendor", "docs", "migrations"] 
  exclude_file = []
  exclude_regex = ["_test.go"]       
  delay = 1000                       
  stop_on_error = true

[log]
  time = true
  color = true                       

[watch]
  dir = "."                          
  recursive = true
